/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Frontmost
 #	author : miyako
 #	2017/05/08
 #
 # --------------------------------------------------------------------------------*/



// --- Frontmost
void Is_application_frontmost(sLONG_PTR *pResult, PackagePtr pParams);
void MAKE_APPLICATION_FRONTMOST(sLONG_PTR *pResult, PackagePtr pParams);

#if VERSIONWIN
#include "Shlwapi.h"
HWND GetMainHWND();
#endif
